### PR TITLE
add Validate class (GH #52)

### PR DESCRIPTION
**Pull request by sbatschelet**
* add Validate class
* migrate all validate helpers in Routes/Profile.pm to new class.

### CODE REVIEW

**Comment by sbatschelet** [comment]
This will be a work in progress as all helpers get migrated and tests added.  But this gets me in the door :camel:

**Comment by SysPete** [comment]
I'd really like to see something like this:
```
my $validator = PerlDance::Validate->new(
    values => $values,
    validator => 'talk',
    tokens => $tokens
);
if ( $validator->valid ) {
    # insert/update and redirect
}
```
I don't want to pass a form since there are times when Dancer::Plugin::Form cannot handle all of my params and if there are errors then I'd like to have this class insert them into the template tokens without me having to do any more work.

**Comment by sbatschelet** [comment]
@SysPete fair points will adjust

**Comment by SysPete** [comment]
Since we now use Dancer::Plugin::DataTransposeValidator (starting at commit 6f5ed9798e95bc4fa497c2d64f905b47f8476b28) this PR is stale so I'm closing it.

**Pull request closed without merging**
